### ISSUE TITLE
Get an error 'cannot read properties 'includes' of undefined ' when using some commands have attachment

### ISSUE THREAD

**Issue by Akio1210** [KanzuXHorizon/Fca-Horizon-Remastered#15]
Before v1.4.8 (I already use 1.4.6), my code is worked normal, but after I update, I get an error message `cannot read properties 'includes' of undefined` 
Please fix it.

**Comment by KanzuXHorizon** [comment]
go to FastConfigFca.json then turn off AntiSendAppState, i'll fix it
